application: postalgone
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /thanks
  static_files: thanks.html
  upload: thanks.html

- url: /static
  static_dir: static

- url: .*
  script: main.py

