application: postalgone
version: 1
runtime: python
api_version: 1

handlers:
- url: /mail
  script: main.py

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(.*\.(js|css))
  static_files: static/\1
  upload: static/.*\.(js|css)

- url: /([^.]*)
  static_files: static/\1.html
  upload: static/.*\.html
